"""Wire format for the solver service.

Everything the solver needs arrives in a single POST body: there is no database
and no server-side session. The frontend owns the problem and sends all of it.
"""

from datetime import date as date_
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


# Ceiling on any single solve. CP-SAT can take unbounded time to *prove*
# infeasibility, so without a cap a hard instance would pin a worker thread and
# an open HTTP request indefinitely.
MAX_SOLVE_SECONDS = 20 * 60

# What a solve is given unless the caller says otherwise. Deliberately far below
# the ceiling: a faculty-sized timetable is a hard optimisation problem that will
# happily use every second it is given without ever proving optimality, and
# nobody watching a demo wants to wait 20 minutes for a schedule that was already
# good after thirty seconds. Raise it in the Settings dialog to grind for a
# better objective.
DEFAULT_SOLVE_SECONDS = 30


class RoomType(str, Enum):
    """Room kinds a subject can require. A session may only be placed in a room
    whose type appears in its subject's `allowedRoomTypes`."""

    lecture = "lecture"
    lab = "lab"
    sports = "sports"
    firing_range = "firing_range"
    # Полигон: outdoor tactical training ground.
    training_ground = "training_ground"


class Role(BaseModel):
    """An academic rank, as data rather than as a fixed enum.

    Everything else the solver reasons about is edited on the Data setup screen;
    ranks used to be the exception, hardcoded here and mirrored by hand in the
    frontend. They are now an ordinary entity, so a faculty can name the ranks it
    actually has and decide what outranks what.
    """

    # Stable, and what Teacher.role points at -- so renaming a rank is free.
    id: str
    # Full label for the dropdown and the roles table, e.g. 'проф. — Professor'.
    name: str
    # Narrow-column label for the teachers table and the ladder, e.g. 'проф.'.
    short: str
    # Priority of the rank, higher wins. This is a *tier key*, not a multiplier:
    # the solver optimises one tier at a time, top down (see timetable_solver.py
    # step 6), so what matters is the ordering and which ranks share a value.
    weight: int = Field(ge=0, le=100)


# The ranks of a Bulgarian faculty, used when a request names no roles of its own
# and as the starting set for a blank project in the UI.
#
# The ids are load-bearing: they are the values the old TeacherRole enum used, so
# a request that omits `roles` and says "role": "professor" -- every seed file and
# every existing caller -- keeps working untouched.
DEFAULT_ROLES = [
    Role(id="professor", name="проф. — Professor", short="проф.", weight=6),
    Role(id="associate_professor", name="доц. — Assoc. Professor", short="доц.", weight=5),
    Role(id="chief_assistant", name="гл. ас. — Chief Assistant", short="гл. ас.", weight=4),
    Role(id="senior_lecturer", name="ст. преп. — Senior Lecturer", short="ст. преп.", weight=3),
    Role(id="lecturer", name="преп. — Lecturer", short="преп.", weight=2),
    Role(id="assistant", name="ас. — Assistant", short="ас.", weight=1),
]

# A teacher with no stated rank shares the bottom tier. This is what keeps the
# feature backwards compatible: a problem with no roles at all yields exactly one
# tier, which is the single-objective behaviour that existed before the ladder.
UNRANKED_WEIGHT = 1


class Slot(BaseModel):
    """One dated teaching slot, e.g. id="2025-09-15-1", date=2025-09-15, period=1.

    Slots are generated by the frontend by expanding its weekday x period template
    across the semester being scheduled. Slots the user has blocked -- and dates
    that fall in a break -- are simply omitted from the request, so the solver
    never needs to know about availability rules: a missing slot is an unusable
    slot. `day` is kept alongside `date` because the weekday is what the UI labels
    columns with and what `blockedSlots` is keyed on.
    """

    id: str
    date: date_
    day: str
    period: int


class SemesterRef(BaseModel):
    """Which semester a request is about.

    Identity is the academic year plus the index within it; the *dates* live per
    group, because two cohorts can run the same semester on different calendars.
    """

    academicYear: str            # "2025/2026"
    index: int = Field(ge=1, le=2)

    @property
    def key(self) -> str:
        return f"{self.academicYear}-{self.index}"


class DateRange(BaseModel):
    """A closed interval of dates. Used for breaks and for spread windows."""

    start: date_
    end: date_
    label: Optional[str] = None

    def contains(self, day: date_) -> bool:
        return self.start <= day <= self.end


class GroupSemester(BaseModel):
    """One group's dates for one semester, holidays included.

    Breaks are excluded from teaching entirely: no session is ever placed on a
    date inside one, and they do not count towards the teaching weeks the even
    spread is measured against.
    """

    academicYear: str
    index: int = Field(ge=1, le=2)
    start: date_
    end: date_
    breaks: List[DateRange] = Field(default_factory=list)

    def teaches_on(self, day: date_) -> bool:
        if not (self.start <= day <= self.end):
            return False
        return not any(b.contains(day) for b in self.breaks)


class SpreadMode(str, Enum):
    """Where inside the semester a subject's sessions are spread."""

    whole = "whole"    # evenly across every teaching week of the semester
    range = "range"    # evenly across a sub-period chosen inside it


class SubjectSemester(BaseModel):
    """How much of a subject runs in one semester.

    A *total* rather than a weekly rate: sessions are placed on real dates, so 20
    sessions across 16 teaching weeks needs no divisibility -- it is 20 dated
    placements, spread as evenly as the week count allows.
    """

    academicYear: str
    index: int = Field(ge=1, le=2)
    totalSessions: int = Field(ge=0, le=400)
    spread: SpreadMode = SpreadMode.whole
    # Required when spread is `range`; ignored otherwise.
    window: Optional[DateRange] = None
    # One or more groups. Every listed group is busy for the whole session.
    # Groups live here rather than on the Subject because a subject can be taught
    # to a different cohort in each semester it runs in.
    groupIds: List[str] = Field(min_length=1)


class Teacher(BaseModel):
    id: str
    name: str
    department: Optional[str] = None
    # Soft: scheduling outside these slots is penalised, never forbidden.
    # An empty list means "no preference", which can never be violated.
    preferredSlots: List[str] = Field(default_factory=list)
    # Soft, and *ranked*: index 0 is the room this teacher most wants, and the
    # cost of a placement is the room's position in the list. A room that is not
    # listed at all costs len(list) -- worse than every ranked choice, but never
    # infinitely worse. Empty means "no preference" and can never be violated.
    preferredRooms: List[str] = Field(default_factory=list)
    # Id of a Role in the request. Optional: absent, or naming a role that is not
    # there, means unranked -- see UNRANKED_WEIGHT.
    role: Optional[str] = None
    # Overrides the weight the role would imply. This is the only way to lift one
    # person out of their rank's tier -- give an assistant a 6 and they negotiate
    # alongside the professors.
    priorityWeight: Optional[int] = Field(default=None, ge=0, le=100)


def effective_weight(teacher: Teacher, roles_by_id: Dict[str, Role]) -> int:
    """Priority tier key for a teacher: explicit override, else rank, else bottom.

    A role id naming no role falls to the bottom tier rather than raising: the UI
    cascades on delete so this should not reach the wire, and quietly demoting a
    teacher is a better failure than refusing to schedule anybody.
    """
    if teacher.priorityWeight is not None:
        return teacher.priorityWeight
    if teacher.role is not None:
        role = roles_by_id.get(teacher.role)
        if role is not None:
            return role.weight
    return UNRANKED_WEIGHT


class Room(BaseModel):
    id: str
    name: str
    capacity: int = Field(ge=0)
    type: RoomType
    building: Optional[str] = None


class Group(BaseModel):
    id: str
    name: str
    size: int = Field(ge=0)
    programme: Optional[str] = None
    # At most two per academic year. A group with no entry for the semester being
    # generated is simply not in term and takes no part in that solve.
    semesters: List[GroupSemester] = Field(default_factory=list)

    def semester(self, ref: SemesterRef) -> Optional[GroupSemester]:
        return next(
            (
                gs
                for gs in self.semesters
                if gs.academicYear == ref.academicYear and gs.index == ref.index
            ),
            None,
        )


class Subject(BaseModel):
    id: str
    name: str
    # One or more acceptable room types. A session may go in any room whose type
    # is in this list -- the solver picks which.
    allowedRoomTypes: List[RoomType] = Field(min_length=1)
    # One entry per semester the subject runs in. A subject with no entry for the
    # semester being generated contributes no sessions to it.
    semesters: List[SubjectSemester] = Field(default_factory=list)
    # Candidate teachers. Exactly one of them teaches each session, chosen by the
    # solver, independently per session. This is a pool, not co-teaching.
    teacherIds: List[str] = Field(min_length=1)

    def semester(self, ref: SemesterRef) -> Optional[SubjectSemester]:
        return next(
            (
                ss
                for ss in self.semesters
                if ss.academicYear == ref.academicYear and ss.index == ref.index
            ),
            None,
        )

    def groups_for(self, ref: SemesterRef) -> List[str]:
        """Groups attending this subject in `ref`; empty when it does not run then."""
        spec = self.semester(ref)
        return list(spec.groupIds) if spec is not None else []

    def all_group_ids(self) -> List[str]:
        """Every group across every semester, deduped, in first-seen order.

        For the checks that are not about one semester -- a dangling group id is a
        data bug whichever term it appears in.
        """
        seen: List[str] = []
        for ss in self.semesters:
            for gid in ss.groupIds:
                if gid not in seen:
                    seen.append(gid)
        return seen


class SearchParams(BaseModel):
    """CP-SAT engine parameters exposed to the UI.

    This model *is* the whitelist: there is no passthrough of arbitrary solver
    proto fields. `None` means "leave CP-SAT's own default alone", which is safer
    than hardcoding today's defaults -- they can shift between OR-Tools versions.

    None of these change which timetables are legal; they change how hard, and how
    repeatably, the solver works to find one.
    """

    numWorkers: int = Field(default=8, ge=1, le=16)
    randomSeed: int = Field(default=0, ge=0)
    presolve: bool = True
    symmetryLevel: Optional[int] = Field(default=None, ge=0, le=4)
    linearizationLevel: Optional[int] = Field(default=None, ge=0, le=2)


class SolveRequest(BaseModel):
    # Which semester this solve is for. Everything else is filtered through it:
    # which groups are in term, which subjects run, and how many sessions each has.
    semester: SemesterRef
    slots: List[Slot]
    # Defaults to the built-in ranks, so a caller that never heard of roles still
    # gets the same tiers it always did.
    roles: List[Role] = Field(default_factory=lambda: list(DEFAULT_ROLES))
    teachers: List[Teacher]
    rooms: List[Room]
    groups: List[Group]
    subjects: List[Subject]
    # Always bounded, and hard-capped at 20 minutes. The default is the cap: run
    # as long as it takes, up to the point where an unattended request would be a
    # runaway rather than a slow answer. On expiry the best solution found so far
    # is returned, and the status says whether it was proven optimal.
    maxTimeInSeconds: float = Field(default=DEFAULT_SOLVE_SECONDS, gt=0.0, le=MAX_SOLVE_SECONDS)
    # Soft-constraint weights. Preference outranks gaps by an order of magnitude
    # so a compact day is never bought at the price of a teacher preference.
    preferenceWeight: int = Field(default=10, ge=0, le=1000)
    # Cost per *rank step* away from a teacher's first-choice room. Below the slot
    # weight on purpose: when the two preferences cannot both be met, the slot is
    # the one worth keeping.
    roomPreferenceWeight: int = Field(default=5, ge=0, le=1000)
    gapWeight: int = Field(default=1, ge=0, le=1000)
    # Take the first legal timetable instead of the best one. The gap between the
    # two is the whole value of optimising, so it is worth being able to see it.
    stopAfterFirstSolution: bool = False
    # Our own symmetry-breaking constraint (see timetable_solver.py step 4).
    # Switchable because CP-SAT's presolve finds symmetry on its own, and whether
    # ours still earns its place is a question this PoC should be able to answer.
    useSymmetryBreaking: bool = True
    search: SearchParams = Field(default_factory=SearchParams)


class Assignment(BaseModel):
    subjectId: str
    subjectName: str
    slot: str
    # The real date this session lands on, so the multi-week grid can place it
    # without re-deriving anything from the slot id.
    date: date_
    roomId: str
    roomName: str
    teacherId: str
    teacherName: str
    groupIds: List[str]
    groupNames: List[str]
    # True when this session missed its teacher's preferred slots or rooms.
    softViolated: bool = False
    softReason: Optional[str] = None
    # Position of the assigned room in the teacher's ranked list: 0 is their first
    # choice, len(list) means the room was not on it. None when they ranked none.
    roomPreferenceRank: Optional[int] = None


class TierResult(BaseModel):
    """What one rung of the priority ladder achieved.

    Without this the ladder is invisible: a single objective number cannot say
    which rank had to give something up, nor whether a rung ran out of time
    before it had finished bargaining.
    """

    weight: int
    # Short labels of the ranks sharing this weight, for the UI to render as-is.
    # Empty when the tier is unranked.
    roles: List[str] = Field(default_factory=list)
    teacherCount: int
    # Weighted slot+room penalty this tier settled for.
    penalty: int
    # OPTIMAL means the tier could do no better; FEASIBLE means it ran out of
    # time and the tiers below were frozen against a possibly-improvable number.
    status: str
    solveTimeSeconds: float


class Stats(BaseModel):
    status: str
    solveTimeSeconds: float
    # Total weighted penalty across every tier plus gaps -- NOT CP-SAT's own
    # ObjectiveValue(), which after the ladder is only the final (gap) phase.
    objectiveValue: Optional[float] = None
    # Only meaningful for a single-objective solve; the ladder leaves it None,
    # because a bound on the last phase is not a bound on the whole.
    bestObjectiveBound: Optional[float] = None
    numSessions: int
    numPlaced: int
    numSlots: int
    numBooleanVariables: int
    preferenceViolations: int
    roomPreferencePenalty: int = 0
    gapPenalty: int
    # Top-down, one entry per distinct teacher weight present in the problem.
    tiers: List[TierResult] = Field(default_factory=list)


class Hint(BaseModel):
    """One reason the problem looks over-subscribed. Title + detail mirrors the
    failure panel in the UI design."""

    title: str
    detail: str


class Validation(BaseModel):
    """Independent re-check of the solver's own output (see
    `timetable_solver.validate_assignments`)."""

    ok: bool
    errors: List[str] = Field(default_factory=list)


class SettingsUsed(BaseModel):
    """Echo of the settings a result was actually produced with.

    Without this the UI would show the *current* settings next to a result that
    was solved under the previous ones.
    """

    maxTimeInSeconds: float
    preferenceWeight: int
    roomPreferenceWeight: int
    gapWeight: int
    stopAfterFirstSolution: bool
    useSymmetryBreaking: bool
    search: SearchParams


class SolveResponse(BaseModel):
    # OPTIMAL | FEASIBLE | INFEASIBLE | UNKNOWN | MODEL_INVALID
    status: str
    message: str
    assignments: List[Assignment] = Field(default_factory=list)
    stats: Optional[Stats] = None
    validation: Optional[Validation] = None
    hints: List[Hint] = Field(default_factory=list)
    settingsUsed: Optional[SettingsUsed] = None
