"""Wire format for the solver service.

Everything the solver needs arrives in a single POST body: there is no database
and no server-side session. The frontend owns the problem and sends all of it.
"""

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


# Ceiling on any single solve. CP-SAT can take unbounded time to *prove*
# infeasibility, so without a cap a hard instance would pin a worker thread and
# an open HTTP request indefinitely.
MAX_SOLVE_SECONDS = 20 * 60

# What a solve is given unless the caller says otherwise. Deliberately far below
# the ceiling: a faculty-sized timetable is a hard optimisation problem that will
# happily use every second it is given without ever proving optimality, and
# nobody watching a demo wants to wait 20 minutes for a schedule that was already
# good after thirty seconds. Raise it in the Settings dialog to grind for a
# better objective.
DEFAULT_SOLVE_SECONDS = 30


class RoomType(str, Enum):
    """Room kinds a subject can require. A session may only be placed in a room
    whose type appears in its subject's `allowedRoomTypes`."""

    lecture = "lecture"
    lab = "lab"
    sports = "sports"
    firing_range = "firing_range"
    # Полигон: outdoor tactical training ground.
    training_ground = "training_ground"


class Slot(BaseModel):
    """One teaching slot, e.g. id="mon-1", day="Mon", period=1.

    Slot ids are generated by the frontend from its day x period config. Slots the
    user has blocked are simply omitted from the request, so the solver never needs
    to know about availability rules -- a missing slot is an unusable slot.
    """

    id: str
    day: str
    period: int


class Teacher(BaseModel):
    id: str
    name: str
    department: Optional[str] = None
    # Soft: scheduling outside these slots is penalised, never forbidden.
    # An empty list means "no preference", which can never be violated.
    preferredSlots: List[str] = Field(default_factory=list)


class Room(BaseModel):
    id: str
    name: str
    capacity: int = Field(ge=0)
    type: RoomType
    building: Optional[str] = None


class Group(BaseModel):
    id: str
    name: str
    size: int = Field(ge=0)
    programme: Optional[str] = None


class Subject(BaseModel):
    id: str
    name: str
    # One or more acceptable room types. A session may go in any room whose type
    # is in this list -- the solver picks which.
    allowedRoomTypes: List[RoomType] = Field(min_length=1)
    sessionsPerWeek: int = Field(ge=0, le=40)
    # Candidate teachers. Exactly one of them teaches each session, chosen by the
    # solver, independently per session. This is a pool, not co-teaching.
    teacherIds: List[str] = Field(min_length=1)
    # One or more groups. Every listed group is busy for the whole session.
    groupIds: List[str] = Field(min_length=1)


class SearchParams(BaseModel):
    """CP-SAT engine parameters exposed to the UI.

    This model *is* the whitelist: there is no passthrough of arbitrary solver
    proto fields. `None` means "leave CP-SAT's own default alone", which is safer
    than hardcoding today's defaults -- they can shift between OR-Tools versions.

    None of these change which timetables are legal; they change how hard, and how
    repeatably, the solver works to find one.
    """

    numWorkers: int = Field(default=8, ge=1, le=16)
    randomSeed: int = Field(default=0, ge=0)
    presolve: bool = True
    symmetryLevel: Optional[int] = Field(default=None, ge=0, le=4)
    linearizationLevel: Optional[int] = Field(default=None, ge=0, le=2)


class SolveRequest(BaseModel):
    slots: List[Slot]
    teachers: List[Teacher]
    rooms: List[Room]
    groups: List[Group]
    subjects: List[Subject]
    # Always bounded, and hard-capped at 20 minutes. The default is the cap: run
    # as long as it takes, up to the point where an unattended request would be a
    # runaway rather than a slow answer. On expiry the best solution found so far
    # is returned, and the status says whether it was proven optimal.
    maxTimeInSeconds: float = Field(default=DEFAULT_SOLVE_SECONDS, gt=0.0, le=MAX_SOLVE_SECONDS)
    # Soft-constraint weights. Preference outranks gaps by an order of magnitude
    # so a compact day is never bought at the price of a teacher preference.
    preferenceWeight: int = Field(default=10, ge=0, le=1000)
    gapWeight: int = Field(default=1, ge=0, le=1000)
    # Take the first legal timetable instead of the best one. The gap between the
    # two is the whole value of optimising, so it is worth being able to see it.
    stopAfterFirstSolution: bool = False
    # Our own symmetry-breaking constraint (see timetable_solver.py step 4).
    # Switchable because CP-SAT's presolve finds symmetry on its own, and whether
    # ours still earns its place is a question this PoC should be able to answer.
    useSymmetryBreaking: bool = True
    search: SearchParams = Field(default_factory=SearchParams)


class Assignment(BaseModel):
    subjectId: str
    subjectName: str
    slot: str
    roomId: str
    roomName: str
    teacherId: str
    teacherName: str
    groupIds: List[str]
    groupNames: List[str]
    # True when this session landed outside its teacher's preferred slots.
    softViolated: bool = False
    softReason: Optional[str] = None


class Stats(BaseModel):
    status: str
    solveTimeSeconds: float
    objectiveValue: Optional[float] = None
    bestObjectiveBound: Optional[float] = None
    numSessions: int
    numPlaced: int
    numSlots: int
    numBooleanVariables: int
    preferenceViolations: int
    gapPenalty: int


class Hint(BaseModel):
    """One reason the problem looks over-subscribed. Title + detail mirrors the
    failure panel in the UI design."""

    title: str
    detail: str


class Validation(BaseModel):
    """Independent re-check of the solver's own output (see
    `timetable_solver.validate_assignments`)."""

    ok: bool
    errors: List[str] = Field(default_factory=list)


class SettingsUsed(BaseModel):
    """Echo of the settings a result was actually produced with.

    Without this the UI would show the *current* settings next to a result that
    was solved under the previous ones.
    """

    maxTimeInSeconds: float
    preferenceWeight: int
    gapWeight: int
    stopAfterFirstSolution: bool
    useSymmetryBreaking: bool
    search: SearchParams


class SolveResponse(BaseModel):
    # OPTIMAL | FEASIBLE | INFEASIBLE | UNKNOWN | MODEL_INVALID
    status: str
    message: str
    assignments: List[Assignment] = Field(default_factory=list)
    stats: Optional[Stats] = None
    validation: Optional[Validation] = None
    hints: List[Hint] = Field(default_factory=list)
    settingsUsed: Optional[SettingsUsed] = None
